title: Nelson's Notebook
subtitle: null
description: 我的博客，记录我的所见、所闻、所思、所学
keywords: 前端 front-end developer
author: Nelson
language:
  - zh-CN
  - en
timezone: null
url: 'http://yoursite.com'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: pln-nelson
plugin:
  - hexo-prism-plugin
prism_plugin:
  mode: preprocess
  theme: default
  line_number: true
search:
  path: search.xml
  field: all
deploy:
  type: git
  repo: 'git@github.com:nelsonxuan/nelsonxuan.github.io.git'
